openapi: 3.0.0
info:
  title: 预检查的接口
  description: 该 API 用于用户执行sql预检查。
  version: 6.0.2
  contact:
    name: wcheng.luo
servers:
  - url: ${scheme}://${host}:${scheme_port}
    description: 接口测试服务器
paths:
  /api/pe/sql/executes/precheck:
    post:
      operationId: precheck
      summary: 预检查
      description: 进行sql预检查。
      requestBody:
        content:
          'application/json':
            schema:
              type: object
              properties:
                limit:
                  description: 分页
                  type: integer
                  example: 200
                offset:
                  description: 大小
                  type: integer
                  example: 0
                origin:
                  description: 未知
                  type: integer
                  example: 1
                connect_id:
                  description: 实例的id
                  type: string
                  example: ${connect_id}
                schema_id:
                  description: schema的id
                  type: string
                  example: ${schema_id}
                charset:
                  description: 字符集
                  type: string
                  example: ""
                token:
                  description: sql窗口的token
                  type: string
                  example: ${sql_token}
                is_account_conn:
                  description: 是否是账号直连
                  type: integer
                  example: 0
                line_feed:
                  description: 未知
                  type: integer
                  example: 0
                auto_select_sql:
                  description: 自动选择sql
                  type: integer
                  example: 0
                date_format:
                  description: 日期格式
                  type: string
                  example: "yyyy-MM-dd"
                time_format:
                  description: 时间格式
                  type: string
                  example: "HH:mm:ss"
                date_time_format:
                  description: 时间格式
                  type: string
                  example: "yyyy-MM-dd HH:mm:ss.SSS"
                use_native_format:
                  description: 未知
                  type: boolean
                  example: true
                prefs:
                  description: sqlserver的首选项
                  type: string
                  example: "2,3,5,6,7"
                auto_connect:
                  description: 是否自动恢复链接
                  type: boolean
                  example: false
                font_size:
                  description: 字体的大小
                  type: integer
                  example: 14
                theme:
                  description: 主题
                  type: string
                  example: 0
                short_connect:
                  description: 是否短连接
                  type: boolean
                  example: false
                auto_commit:
                  description: 是否自动提交
                  type: boolean
                  example: true
                is_first_precheck:
                  description: 预检查？
                  type: boolean
                  example: false
                sql:
                  description: 传入的sql语句
                  type: string
                  example: ${sql}
              required:
                - limit
                - offset
                - origin
                - connect_id
                - schema_id
                - charset
                - token
                - is_account_conn
                - line_feed
                - auto_select_sql
                - date_format
                - time_format
                - date_time_format
                - use_native_format
                - prefs
                - auto_connect
                - font_size
                - theme
                - short_connect
                - auto_commit
                - is_first_precheck
                - sql
      responses:
        "200":
          description: 操作成功
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/PrecheckResponse'
components:
  schemas:
    PrecheckResponse:
      type: object
      properties:
        status:
          type: integer
          description: 接口成功状态码
        message:
          type: string
          description: 接口成功信息
        data:
          $ref: '#/components/schemas/PrecheckInfo'
      required:
        - status
        - message
        - data
    PrecheckInfo:
      type: object
      properties:
        status:
          type: integer
          nullable: true
        review_type:
          type: integer
        is_execute_trigger:
          type: integer
        sqls:
          type: array
          items:
            type: string
        params_sqls:
          type: string
          nullable: true