openapi: 3.0.0
info:
  title: 获取用户的auth接口
  description: 该 API 用于获取用户的auth信息。
  version: 6.0.2
  contact:
    name: wcheng.luo
servers:
  - url: ${scheme}://${host}:${scheme_port}
    description: 接口测试服务器
paths:
  /api/test/system/users/getauth:
    get:
      operationId: get_auth
      summary: 获取auth
      description: 获取auth
      parameters:
        - in: query
          name: offset
          schema:
            type: integer
          description: 分页
          example: 0
        - in: query
          name: limit
          schema:
            type: integer
          description: 大小
          example: 10
        - in: query
          name: sk
          schema:
            type: integer
          description: 秘钥
          example: 000111222333222111000
        - in: query
          name: username
          schema:
            type: string
          description: 用户
          example: ${username}
      responses:
        "200":
          description: 操作成功
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/SchemasResponse'
components:
  schemas:
    SchemasResponse:
      type: object
      properties:
        status:
          type: integer
          description: 接口成功状态码
        message:
          type: string
          description: 接口成功信息
        data:
          type: array
          items:
            type: object
      required:
        - status
        - message
        - data